# Generated by Django 3.1.5 on 2021-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('eID', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Address',
        ),
        migrations.AlterField(
            model_name='staff',
            name='eID',
            field=models.IntegerField(),
        ),
    ]
